### ISSUE TITLE
Unnecessary warnings

### ISSUE THREAD

**Issue by sfrode** [basefarm/aws-session-tool#10]
fsa@square:~/.aws$ get_session -d
\# Warning: you did not input an MFA token. Proceed at your own risk.

fsa@square:~/.aws$ get_session -u
upload: ./awsops_session-tool_roles.cfg to s3://bf-aws-tools-session-tool/session-tool_roles.cfg
\# Warning: you did not input an MFA token. Proceed at your own risk.

As the MFA is not required in this case as I already have a valid session, I don't see why I get a warning after a successful download/upload. I recommend removing these confusing warnings.

**Comment by bentterp** [comment]
This was solved by making up and download into separate actions
