### ISSUE TITLE
Ability to specify session timeout

### ISSUE THREAD

**Issue by arnvid** [basefarm/aws-session-tool#11]
Allow longer sessions than 12 hours - many of us work longer than 12 hours. This only requires 2 changes:

-                                       local expiry_s=$(expr $(date -r $f '+%s') + 43200 )
+                                       local expiry_s=$(expr $(date -r $f '+%s') + $MY_EXPIRY )

-                       local JSON=$(aws --output json --profile $AWS_PROFILE sts get-session-token --serial-number=$AWS_SERIAL --token-code $MFA )
+                       local JSON=$(aws --output json --profile $AWS_PROFILE sts get-session-token --serial-number=$AWS_SERIAL --duration-seconds= $MY_EXPIRY --token-code $MFA )

+ some code to allow this to be saved etc,

**Comment by bentterp** [comment]
This was not possible earlier, but they've gone and changed it: "Credentials that are created by IAM users are valid for the duration that you specify, from 900 seconds (15 minutes) up to a maximum of 129600 seconds (36 hours), with a default of 43200 seconds (12 hours)" - maximum used to be 12 hours.

I vote we just change it to something larger, like 20 hours.

**Comment by sfrode** [comment]
The maximum value was 36 hours when Bjørn and I discussed it. We landed on 12 hour as a middle ground; refreshing your session once isn't that much trouble.

I vote to keep it at 12 hours.

**Comment by bjornrog** [comment]
I think that both from a security perspective and a work-life balance perspective, we keep it at 12 hours. Let the 12 hour timeout be a reminder to prioritize your family and/or remember to register your overtime hours correctly.

**Comment by sfrode** [comment]
WontFix
