### ISSUE TITLE
get_session -d resets your session

### ISSUE THREAD

**Issue by sfrode** [basefarm/aws-session-tool#12]
If you have a working session and do a "get_session -d", your current session becomes corrupted and has to be restored from file.

I suggest that instead of having it as a option, we download the file (or check for updates) every time you refresh your session to ensure that you always have an up-to-date list of roles to be assumed.

**Comment by bentterp** [comment]
I think the most logical would be to get the list when you obtain a session, as it's done without session privs.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by bjornrog** [comment]
Maybe, we could try that. But let's make sure the tool doesn't take too long to complete. Nice to keep it as snappy as possible.

**Comment by bentterp** [comment]
Simplest would be to let download be a stand-alone operation, similar to upload. The problems only arise becuase somebody wanted to be able to do the download as part of the morning ritual.
