### ISSUE TITLE
starting a terminal without a working internetconnection 

### ISSUE THREAD

**Issue by tbondal** [basefarm/aws-session-tool#13]
If I start a terminal window without a working/slow internet connection i guess it will trying to check for a new version and it will time out after some time.
The feedback is then:
"WARN: Your version of session-tool is outdated! You have 1.4.6, the latest is   "

Two things
1: I have to wait for the connection to time out before the terminal window opens  (takes time to open the terminal)
2: I have the latest version

OK - I guess this is not big issue - usually you have a working Internet connection. But I'm commuting with NSB and there the connectivity is at best very limited.

a small cosmetic thing...

**Comment by bjornrog** [comment]
Various improvements was done to session tool for making sure the delay when working offline is as small as possible. These changes have been in session tool for mor than a year now.
