### ISSUE TITLE
Pre-req timeout does not exist on macos?

### ISSUE THREAD

**Issue by arnvid** [basefarm/aws-session-tool#14]
Last login: Wed Jun 20 11:31:39 on ttys002
-bash: timeout: command not found
alk-mbp:~ alk$

**Comment by bentterp** [comment]
OSX is both pretty and Unix-like, but the pretty parts ain't Unix-like and the Unix-like parts ain't pretty.

**Comment by bentterp** [comment]
@arnvid could you test this alternative - the perl function?
https://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x

**Comment by arnvid** [comment]
alk-mbp:~ alk$ brew install coreutils
.bashrc:
alias timeout="gtimeout"

**Comment by arnvid** [comment]
@bentterp  - workaround but not pretty :)

**Comment by bentterp** [comment]
Our esteemed collegue @bjornrog just pointed out that curl has it's own built-in timeout function....

**Comment by bentterp** [comment]
@arnvid Does 1.4.8 solve the issue for you?

**Comment by arnvid** [comment]
This is fixed
