### ISSUE TITLE
Session tool not working when passing --profile option on CLI

### ISSUE THREAD

**Issue by GeoffBarnettSTHLM** [basefarm/aws-session-tool#22]
Using session tool I have my default profile in ~/.aws/config set to use the profile awsops.
When authenticating with session tool and assuming a role, I am able to use the privileges of the role, by using the default profile, however, when I use the --profile option in the awscli to set the profile explicitly, the profile fails.

I noticed that in the ~/.aws/credentials file the credentials for the default profile and the awsops profiles do not match, given that the default profile is the awsops profile, these credential entries should be identical and updated at the same time.

When using 'rotate_credentials -n -p awsops' only the awsops profile is updated, not the default profile.

I can easily reproduce the failure with a simple test.
Assume role for ka2-awspreprod-admin
At the CLI run the following commands:
aws s3 ls
aws s3 ls --profile awsops
When using --profile the command fails to list buckets.

I am using the zsh branch of session tool, the issue occurs under both zsh and bash shells on my mac.

aws --version
aws-cli/1.17.0 Python/3.8.1 Darwin/19.2.0 botocore/1.14.0

**Comment by GeoffBarnettSTHLM** [comment]
User education issue, this is not a fault, however docs should be updated to describe how session tool operates to make troubleshooting easier.

**Comment by bjornrog** [comment]
Yes, agree. Will keep this open until it's fixed.

**Comment by bjornrog** [comment]
Hmm, rethinking this issue. First the user does a `assume_role` then, list s3 buckets.

The awsops profile (or whatever the user opted to name the profile used by session tool), is not the same as the assumed role. The assumed role is not available as a profile in ~/.aws/config or credentials. It's only available in the environment variables.

The given example is expected to fail. This is essential understanding of what session tool does. Really not related to session tool either, it's how IAM with assume role work.

So will close this issue.
