### ISSUE TITLE
MacOS - get_session breaks on date ...

### ISSUE THREAD

**Issue by arnvid** [basefarm/aws-session-tool#23]
alk@alk-mbp - ~: get_session -s #######
Failed conversion of ``2020-01-06T07:39:27+00:00'' using format ``%Y-%m-%dT%H:%M:%SZ''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: option requires an argument -- r
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
expr: syntax error
date: option requires an argument -- r
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
expr: syntax error
date: option requires an argument -- r
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
-bash: [: : integer expression expected
Failed conversion of ``2020-02-15T21:23:43+00:00'' using format ``%Y-%m-%dT%H:%M:%SZ''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: option requires an argument -- r
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

**Comment by bjornrog** [comment]
I suspect you have replaced the macOS provided date with gnudate.

ls -l `which date`

We'll have to rewrite session tool to hardcode paths to supporting utilities or automatically detect the version of tool being used.

**Comment by arnvid** [comment]
alk@alk-mbp - ~: which date
/bin/date
alk@alk-mbp - ~: ls -la /bin/date
-rwxr-xr-x  1 root  wheel  41728 Jan 23 14:59 /bin/date
alk@alk-mbp - ~: date
Fri Feb 14 15:08:59 CET 2020
alk@alk-mbp - ~:

**Comment by bjornrog** [comment]
Aha, I think this is AWS cli 2 ? Previously aws cli returned expiry in the format 2020-02-16T20:30:51Z

You got it in the format 2020-01-06T07:39:27+00:00

There is an age check function that tries to verify that the session is still valid. It's failing that validation.

**Comment by arnvid** [comment]
date format from AWS Cli v2 is the culprit.. Opened another issue where this is described with workaround

**Comment by arnvid** [comment]
Replaced by #26
