### ISSUE TITLE
MacOS - get_session -s/-r breaks and no session is stored.

### ISSUE THREAD

**Issue by arnvid** [basefarm/aws-session-tool#24]
alk@alk-mbp - ~: get_session -r
enter aes-256-cbc decryption password:
ERROR: You do not seem to have a valid session in your environment.
alk@alk-mbp - ~:

**Comment by arnvid** [comment]
lk@alk-mbp - ~: get_console_url far-awsprod-bfadmin
ERROR: You do not seem to have a valid session in your environment.

**Comment by bjornrog** [comment]
Maybe related to the date issues maybe related to aws cli2?
To assist in debugging, maybe you can re-run like this:
$ set -x
$ get_session -r
$ set +x

And paste the output into this ticket?

**Comment by arnvid** [comment]
++ date -j -u -f %Y-%m-%dT%H:%M:%SZ 2020-02-18T19:38:12+00:00 +%s
Failed conversion of ``2020-02-18T19:38:12+00:00'' using format ``%Y-%m-%dT%H:%M:%SZ''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

**Comment by arnvid** [comment]
date -j -u -f "%Y-%m-%dT%H:%M:%S+%H:00" 2020-02-18T19:47:41+01:00 +%s
1581990461

**Comment by arnvid** [comment]
Superseded by #26
