### ISSUE TITLE
MacOS - brew now installs AWS cli v2

### ISSUE THREAD

**Issue by arnvid** [basefarm/aws-session-tool#25]
aws-cli/2.0.0 Python/3.8.1 Darwin/19.3.0 botocore/2.0.0dev4

**Comment by arnvid** [comment]
New version of botocore and aws cli on newer macbooks

**Comment by arnvid** [comment]
Causes issues like the one in #26

**Comment by bjornrog** [comment]
1.5.8 supports AWS cli v2.
