### ISSUE TITLE
AWS CLI version 2 now returns all timestamp output values in ISO 8601 format

### ISSUE THREAD

**Issue by arnvid** [basefarm/aws-session-tool#26]
By default, AWS CLI version 2 returns all timestamp response values in the ISO 8601 format. In AWS
CLI version 1, commands returned timestamp values in whatever format was returned by the HTTP API
response, which could vary from service to service.

**Comment by arnvid** [comment]
ISO 8601 formatted timestamps look like the following examples. The first example shows the time in
Coordinated Universal Time (UTC) by including a Z after the time. The date and the time are separated
by a T.
`2019-10-31T22:21:41Z`

To specify a different time zone, instead of the Z, specify a + or - and the number of hours the desired
time zone is ahead of or behind UTC, as a two-digit value. The following example shows the same time
as the previous example but adjusted to Pacific Standard time, which is eight hours behind UTC.
`2019-10-31T14:21:41-08`

To see timestamps in the format returned by the HTTP API response, add the following line to your
.aws/config profile.
`cli_timestamp_format = wire`

**Comment by bjornrog** [comment]
1.5.8 support AWS cli v2, handling both the old and the new date formats, so we do not care about your cli_timestamp_format setting.
