### ISSUE TITLE
Version warning is not specific enough

### ISSUE THREAD

**Issue by kimma-basefarm** [basefarm/aws-session-tool#3]
When opening a new terminal, it sources the session-tool.sh automatically (since it's in my profile).
The session-tool then checks if there is a newer version available, and prints this:
WARN: Your version is outdated! You have 1.4.2, the latest is 

There should be an indication that it is actually session tool that prints this error, right now it can be any program that loads when you open a terminal window.

(Also, the "the latest is" is just empty, which i guess is a bug).

**Comment by bentterp** [comment]
this has been fixed, please do a new pull

**Comment by kimma-basefarm** [comment]
Pulled new version, but since i'm on the new version i can't actually test if it works.
I'll take your word for it ;)

**Comment by bentterp** [comment]
Tested by changing locally to 1.4.4:
Using username "bent".
Authenticating with public key "rsa-key-20160824 bent.terp@basefarm.com bent@terp.se" from agent
Last login: Wed Nov  1 14:50:54 2017 from 192.168.65.129
WARN: Your version of session-tool is outdated! You have 1.4.4, the latest is 1.4.3
[bent@c7vm ~]$
