### ISSUE TITLE
sessions tools not saving profile, missing roles and such 

### ISSUE THREAD

**Issue by arnvid** [basefarm/aws-session-tool#4]
I swapped from the old bf_aws_tools to aws-session-tool
After the first time I ran it then logged back in it seems it has a slight amount of amnesia.

workhorse ~ # su - aws-ops
ERROR: SHELL is not bash. session_tools will not work.
aws-ops@workhorse ~ $ bash
aws-ops@workhorse ~ $ get_session -s xxxxxxxx
ERROR: No profile specified and no default profile configured.

*** first one.. not remembering the cached session,

aws-ops@workhorse ~ $ get_session -p default -s xxxxxxx
enter aes-256-cbc encryption password:
Verifying - enter aes-256-cbc encryption password:

aws-ops@workhorse ~ $ get_console_url far-awsprod-admin
ERROR: Neither ~/.aws/default_session-tool_roles.cfg nor ~/.aws/default_roles.cfg found, please run get_session -d or create ~/.aws/default_roles.cfg

Then it does not know the roles anymore.

aws-ops@workhorse ~ $ get_session -l
awsops 02:15:32 2017-11-25 (EXPIRED)
default 10:20:43 2017-11-27

aws-ops@workhorse ~ $ get_console_url -l
ERROR: Neither ~/.aws/default_session-tool_roles.cfg nor ~/.aws/default_roles.cfg found, please run get_session -d or create ~/.aws/default_roles.cfg

aws-ops@workhorse ~ $ get_session -d
ERROR: No bucket configure to download roles from. Please configure with: aws configure set session-tool_bucketname <BUCKETNAME> --profile default

looking in the old session tools I found a bucket - hope thats the one we should be using ;)

aws-ops@workhorse ~ $ aws configure set session-tool_bucketname XX-XXX-XXX-XXXXX-tool  --profile default
aws-ops@workhorse ~ $ get_session -d
# Warning: you did not input an MFA token. Proceed at your own risk.

aws-ops@workhorse ~ $ get_session -d -s XXXXXXX
enter aes-256-cbc encryption password:
Verifying - enter aes-256-cbc encryption password:

And then it works ;)

**Comment by bentterp** [comment]
After configuring  session-tool_bucketname and default.session_tool_default_profile, have you had other issues?

The name of the bucket to download rolelist from is specific for the account containing the IAM users and groups. I have improved our internal "Tooling and coding" documentation with info about this - obviously something I should have done from the beginning, sorry!

**Comment by arnvid** [comment]
get_session  -s XXXXXX
ERROR: No profile specified and no default profile configured.

**Comment by arnvid** [comment]
aws-ops@workhorse ~ $ more .aws/config
[default]
region = eu-west-1
session_tool_default_profile = awsops
[preview]
cloudfront = true
[profile default]
session-tool_bucketname = bf-aws-tools-session-tool
[profile awsops]
session-tool_bucketname = bf-aws-tools-session-tool

get_session -d
ERROR: No profile specified and no default profile configured.


.aws/
awsops.aes                      bf-roles.cfg                    credentials                     default_session-tool_roles.cfg
awsops_session-tool_roles.cfg   config                          default.aes                     roles.cfg

get_session -l
awsops 23:22:07 2017-12-01 (EXPIRED)
default 10:41:26 2017-11-27 (EXPIRED)


Still not working w/o running  -p awsops on the first get_session

 get_session -p awsops -s -d XXXXXX

then it caches it until it you logout..

**Comment by bentterp** [comment]
Our tests show that you might resolve this by removing the [profile default] section. Default values should be configured in the [default] section, both for aws-session-tool and for aws cli.

Could you please try and merge those two sections in both config and credentials?

**Comment by bentterp** [comment]
Closed due to inactivity
